baseurl = "https://nevilletrucking.com"
defaultContentLanguage = "en"
googleAnalytics = ""
languageCode = "en-us"
paginate = 10
theme = "hugo-universal-theme"
themesDir = "./themes"
title = "Neville Trucking"
[Permalinks]
blog = "/blog/:year/:month/:day/:filename/"
[[menu.main]]
identifier = "Home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "Services"
name = "Services"
url = "/services/"
weight = 2
[[menu.main]]
identifier = "Pay Bill"
name = "Pay Bill"
url = "/billing/"
weight = 3
[[menu.main]]
identifier = "Contact Us"
name = "Contact Us"
url = "/contact/"
weight = 4
[[menu.topbar]]
name = "Email"
pre = "<i class='fas fa-2x fa-envelope'></i>"
url = "mailto:nevilletrucking@yahoo.com"
weight = 2
[params]
about_us = "<p>Ben E. Neville Trucking Service, Inc. was established as a small, family operated business over 55 years ago by Ben and Theresa Neville when they began providing trash service for friends and neighbors in their hometown of Minier, IL."
address = "<p class=\"text-uppercase\"><strong>Ben E Neville Trucking, Inc.</strong>\n        <br>PO Box 1059\n        <br>Mackinaw, IL 61755\n        <br>\n        <strong>(309) 359-8400</strong>\n      </p>\n      "
author = "Ben E. Neville"
contact_form_ajax = false
copyright = "Copyright (c) 2019, Neville Trucking; all rights reserved."
date_format = "January 2, 2006"
defaultDescription = "Dumpster and waste service for Central Illinois"
defaultKeywords = ["Trash", "Dumpster", "Commercial", "Residential", "Roll-off", "Central Illinois"]
default_sharing_image = "img/logo.png"
email = "nevilletrucking@yahoo.com"
facebook_site = ""
googleMapsApiKey = ""
latitude = "-12.043333"
logo = "img/logo.png"
logo_small = "img/logo-small.png"
longitude = "-77.028333"
mainSections = ["blog"]
style = "green"
twitter_site = "nevilletrucking"
viewMorePostLink = "/blog/"
[params.carousel]
enable = true
[params.recent_posts]
enable = false
subtitle = ""
title = "From our blog"
[params.see_more]
enable = true
icon = "far fa-file-alt"
link_text = "Make Payment"
link_url = "#"
subtitle = "Make a one-time payment using our online payment portal"
title = "Pay My Bill"
[params.service_areas]
enable = false
subtitle = ""
title = "Areas Served"
[params.services]
enable = true
[params.testimonials]
enable = false 
subtitle = "We have worked with many service-areas and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our service-areas said about us."
title = "Testimonials"
[params.topbar]
enable = true
text = "<p class=\"hidden-sm hidden-xs\" style=\"padding-top:5px;\">Contact us at 309-359-8400 or <a href=\"mailto:nevilletrucking@yahoo.com\">nevilletrucking@yahoo.com</a>.</p>\n      <p class=\"hidden-md hidden-lg\"><a href=\"#\" data-animate-hover=\"pulse\"><i class=\"fas fa-phone\"></i></a>\n      <a href=\"#\" data-animate-hover=\"pulse\"><i class=\"fas fa-envelope\"></i></a>\n      </p>\n      "
[params.widgets]
categories = true
search = true
tags = true
