---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: config.toml
  label: Global Config
- type: document
  path: README.md
  label: README
- type: directory
  path: themes/hugo-universial-theme/layouts
  label: Layouts
  create: all
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: data
  label: Data
  create: all
  match: "**/*"
  new_doc_ext: yaml
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.59.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.59.1
